[profile.default]
libs = ['lib']
src = 'attack/contracts'
test = 'attack/test'
out = 'attack/out'
cache_path = 'attack/cache'

optimizer = true
optimizer_runs = 9999
ignored_error_codes = [ 2072, 5159, 9302 ]
