#![allow(clippy::all)]
//! This lib contains abigen! generated bindings for solidity contracts.
//! This is autogenerated code.
//! Do not manually edit these files.
//! These files may be overwritten by the codegen system at any time.
pub mod coin_flip;
pub mod damn_valuable_token;
pub mod erc20;
pub mod erc4626;
pub mod fallback;
pub mod fixed_point_math_lib;
pub mod ierc3156;
pub mod ierc3156_flash_borrower;
pub mod ierc3156_flash_lender;
pub mod owned;
pub mod receiver_unstoppable;
pub mod reentrancy_guard;
pub mod safe_transfer_lib;
pub mod unstoppable_vault;
