name: CI

on:
  push:
    branches:
      - 0xgleb/solutions
      - sojaleiss/solutions
  workflow_dispatch:
  pull_request:

env:
  FOUNDRY_PROFILE: ci

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install Foundry
        uses: onbjerg/foundry-toolchain@v1

      - name: Check Solidity formatting
        run: forge fmt --check

      - name: Build contracts
        run: forge build

      - name: Install toolchain
        uses: dtolnay/rust-toolchain@stable

      - uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: true

      - name: Build crates
        run: cargo build --workspace --all-targets

      - name: Lint
        run: cargo clippy

      - name: Check solutions
        run: cargo test -p attack -- --nocapture